import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import './globals.css'
import { Sidebar } from '@/components/sidebar'
import { twMerge } from 'tailwind-merge'
import { SupabaseProvider } from '@/providers/SupabaseProvider'
import { UserProvider } from '@/providers/UserProvider'
import { ModalProvider } from '@/providers/ModalProvider'
import { ToasterProvider } from '@/providers/ToasterProvider'
import getSongsByUserId from '@/actions/getSongsByUserId'
import { Player } from '@/components/player'
import usePlayer from '@/hooks/usePlayer'
import { LayoutContainer } from '@/components/layout-container'

const font = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Spotify Clone',
  description: 'Generated by create next app',
}

export const revalidate = 0

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const usersSongs = await getSongsByUserId()
  return (
    <html lang="en">
      <body className={twMerge(
        ``, font.className
      )}>
        <ToasterProvider />
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider />
            <LayoutContainer songs={usersSongs}>
              {children}
            </LayoutContainer>
            <Player />
          </UserProvider>
        </SupabaseProvider>

      </body>
    </html>
  )
}
