import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import './globals.css'
import { Sidebar } from '@/components/sidebar'
import { twMerge } from 'tailwind-merge'
import { SupabaseProvider } from '@/providers/SupabaseProvider'
import { UserProvider } from '@/providers/UserProvider'
import { ModalProvider } from '@/providers/ModalProvider'

const font = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Spotify Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={twMerge(
        `grid grid-cols-1 md:grid-cols-[300px_1fr] gap-x-2`, font.className
      )}>
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider />
            <Sidebar />
            <main className='py-2 overflow-y-auto'>
              {children}
            </main>
          </UserProvider>
        </SupabaseProvider>

      </body>
    </html>
  )
}
